<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyPcBuild.ServiceDefaults\MyPcBuild.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.AI.Inference" Version="13.2.1-preview.1.26180.6" />
    <PackageReference Include="Marten" Version="8.28.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.18" />
    <PackageReference Include="Weasel.Core" Version="8.11.2" />
  </ItemGroup>

</Project>
